In [4]:
# File paths
principals = "N:/Instruction/Instruction Office/SIP-DIP/18-19SIP/Principal Data 18-19.xlsx"
ode_report_card = "N:/Instruction/Instruction Office/SIP-DIP/18-19SIP/StudentEnrollmentSummary_2243.xlsx"
kindy = "N:/Instruction/Instruction Office/SIP-DIP/18-19SIP/ka_lookback_report.xlsx"
sbac_1415 = "N:/Instruction/Instruction Office/SIP-DIP/17-18SIP/CR - SBAC/SBACStuPerfSumm1415final.xlsx"
sbac_1516 = "N:/Instruction/Instruction Office/SIP-DIP/17-18SIP/CR - SBAC/SBACStuPerfSumm1516final.xlsx"
sbac_1617 = "N:/Instruction/Instruction Office/SIP-DIP/17-18SIP/CR - SBAC/SBACStuPerfSumm1617final.xlsx"
sbac_1718 = 'N:/Instruction/Instruction Office/SIP-DIP/18-19SIP/1718SBAC_9_6_18.xlsx'
sbac_growth_1415 = 'N:/Instruction/Data/StratPlanReporting/Academic Growth/AcademicGrowth1415.xls'
sbac_growth_1516 = 'N:/Instruction/Data/StratPlanReporting/Academic Growth/AcademicGrowth1516.xls'
sbac_growth_1617 = 'N:/Instruction/Data/StratPlanReporting/Academic Growth/AcademicGrowth1617.xls'
sbac_growth_1718 = 'N:/Instruction/Instruction Office/SIP-DIP/18-19SIP/AcademicGrowth1718.xlsx'
parti_rates = "N:/Instruction/Instruction Office/SIP-DIP/18-19SIP/StudentSurveyPartiRates1718.xlsx"
attendance = "N:/Instruction/Data/StratPlanReporting/_StrategicMeasures/Missing10daysorfewer.xlsx"
equ_crt = 'N:/Instruction/Data/StratPlanReporting/_Internal Measures/EQU_CRT.xlsx'
six_measures = 'N:/Instruction/Data/StratPlanReporting/SixMeasures/SixMeasures_Survey.xlsx'
staff = 'N:/Instruction/Instruction Office/SIP-DIP/18-19SIP/Staff Voice1718.xlsx'
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None

In [2]:
school = input("school code: ")
school = int(school)

school code: 1160

In [31]:
#read principal file into data frame
principal_data = pd.read_excel(principals, names=['cost_center', 'school_name', 'principal', 'yrs_in_current_position', 'yrs_as_principal', 'total_district_yrs', 'employee_master_screen'], usecols=[0,1,2,3,4,5,6])

ode_rc = pd.read_excel(ode_report_card, names=['school_id', 'grade_level', 'enrollment', 'latino','white','black','asian', 'pacific_islander', 'multiracial', 'native_american', 'swd', 'econdis', 'everell', 'languages_spoken'], usecols=[3,5,6,7,8,9,10,11,12,13,14,15,16,17])

#Oregon Kindergarten Assessment into df
#kindy_1718 = pd.read_excel(kindy, sheetname = '1718ka', index_col=None, names=['school_id', 'school_name', 'student_group', 'app_to_learning', 'app_to_learning_denom', 'num_and_ops', 'num_and_ops_denom', 'letter_names', 'letter_names_denom', 'letter_sounds', 'letter_sounds_denom'], usecols=[0,1,4,7,8,9,10,11,13,16,17])
kindy_1617 = pd.read_excel(kindy, sheetname = '1617ka', index_col=None, names=['school_id', 'school_name', 'student_group', 'app_to_learning', 'app_to_learning_denom', 'num_and_ops', 'num_and_ops_denom', 'letter_names', 'letter_names_denom', 'letter_sounds', 'letter_sounds_denom'], usecols=[0,1,3,7,8,9,10,13,17,18,19])
kindy_1516 = pd.read_excel(kindy, sheetname = '1516ka', index_col=None, names=['school_id', 'school_name', 'student_group', 'app_to_learning', 'app_to_learning_denom', 'num_and_ops', 'num_and_ops_denom', 'letter_names', 'letter_names_denom', 'letter_sounds', 'letter_sounds_denom'], usecols=[0,1,3,7,8,9,10,11,12,13,14])
kindy_1415 = pd.read_excel(kindy, sheetname = '1415ka', index_col=None, names=['school_id', 'school_name', 'student_group', 'app_to_learning', 'app_to_learning_denom', 'num_and_ops', 'num_and_ops_denom', 'letter_names', 'letter_names_denom', 'letter_sounds', 'letter_sounds_denom'], usecols=[0,1,3,6,7,8,9,10,11,12,12,13])

# read SBAC files into data frames
sbac_1415_ela = pd.read_excel(sbac_1415, sheetname = '1415ELARCPerf', index_col=None, names=['school_id', 'school_name', 'student_group', 'grade_group', 'percent_met', 'performance_denominator'], usecols=[0,1,2,3,4,8])
sbac_1415_math = pd.read_excel(sbac_1415, sheetname= '1415MathRCPerf', index_col=None, names=['school_id', 'school_name', 'student_group', 'grade_group', 'percent_met', 'performance_denominator'], usecols=[0,1,3,4,5,9])

sbac_1516_ela = pd.read_excel(sbac_1516, sheetname = '1516ELARCPerf', index_col=None, names=['school_id', 'school_name', 'student_group', 'grade_group', 'percent_met', 'performance_denominator'], usecols=[0,1,2,3,4,8])
sbac_1516_math = pd.read_excel(sbac_1516, sheetname= '1516MathRCPerf', index_col=None, names=['school_id', 'school_name', 'student_group', 'grade_group', 'percent_met', 'performance_denominator'], usecols=[0,1,2,3,4,8])

sbac_1617_ela = pd.read_excel(sbac_1617, sheetname = '1617ELARCPerf', index_col=None, names=['school_id', 'school_name', 'student_group', 'grade_group', 'percent_met', 'performance_denominator'], usecols=[0,1,4,5,6,10])
sbac_1617_math = pd.read_excel(sbac_1617, sheetname= '1617MathRCPerf', index_col=None, names=['school_id', 'school_name', 'student_group', 'grade_group', 'percent_met', 'performance_denominator'], usecols=[0,1,4,5,6,10])

sbac_1718_both = pd.read_excel(sbac_1718, index_col=None, names=['school_id', 'grade_group', 'school_name', 'student_group', 'ela1718partirate', 'ela1718perfdenom', 'ela_pct_met', 'ela1718mgp', 'math1718partirate', 'math1718perfdenom', 'math_pct_met', 'math1718mgp'])

growth_1415_ela = pd.read_excel(sbac_growth_1415, sheetname = 'CCRGrowthdisaggbyschoolELASB', names=['school_id', 'school_name', 'All Students', 'Asian', 'Black', 'Hispanic/Latino', 'Multiracial', 'White', 'Female', 'Male', 'Economically Disadvantaged', 'Special Education', 'Talented and Gifted', 'English Language Learner'], usecols=[0,1,2,3,4,5,6,7,8,9,10,11,12,13], header=None)
growth_1415_math = pd.read_excel(sbac_growth_1415, sheetname = 'CCRGrowthdisaggbyschoolMathSB', names=['school_id', 'school_name', 'All Students', 'Asian', 'Black', 'Hispanic/Latino', 'Multiracial', 'White', 'Female', 'Male', 'Economically Disadvantaged', 'Special Education', 'Talented and Gifted', 'English Language Learner'], usecols=[0,1,2,3,4,5,6,7,8,9,10,11,12,13], header=None)
growth_1516_ela = pd.read_excel(sbac_growth_1516, sheetname = 'CCRGrowthdisaggbyschoolELASB', names=['school_id', 'school_name', 'All Students', 'Asian', 'Black', 'Hispanic/Latino', 'Multiracial', 'White', 'Female', 'Male', 'Economically Disadvantaged', 'Special Education', 'Talented and Gifted', 'English Language Learner'], usecols=[0,1,2,3,4,5,6,7,8,9,10,11,12,13], header=None)
growth_1516_math = pd.read_excel(sbac_growth_1516, sheetname = 'CCRGrowthdisaggbyschoolMathSB', names=['school_id', 'school_name', 'All Students', 'Asian', 'Black', 'Hispanic/Latino', 'Multiracial', 'White', 'Female', 'Male', 'Economically Disadvantaged', 'Special Education', 'Talented and Gifted', 'English Language Learner'], usecols=[0,1,2,3,4,5,6,7,8,9,10,11,12,13], header=None)
growth_1617_ela = pd.read_excel(sbac_growth_1617, sheetname = 'CCRGrowthdisaggbyschoolELASB', names=['school_id', 'school_name', 'All Students', 'Asian', 'Black', 'Hispanic/Latino', 'Multiracial', 'White', 'Female', 'Male', 'Economically Disadvantaged', 'Special Education', 'Talented and Gifted', 'English Language Learner'], usecols=[0,1,2,3,4,5,6,7,8,9,10,11,12,13], header=None)
growth_1617_math = pd.read_excel(sbac_growth_1617, sheetname = 'CCRGrowthdisaggbyschoolMathSB', names=['school_id', 'school_name', 'All Students', 'Asian', 'Black', 'Hispanic/Latino', 'Multiracial', 'White', 'Female', 'Male', 'Economically Disadvantaged', 'Special Education', 'Talented and Gifted', 'English Language Learner'], usecols=[0,1,2,3,4,5,6,7,8,9,10,11,12,13], header=None)
growth_1718_math = pd.read_excel(sbac_growth_1718, sheetname = 'CCRdisaggbyschoolMathSB', names=['school_id', 'school_name', 'All Students', 'Asian', 'Black', 'Hispanic/Latino', 'Multiracial', 'White', 'Female', 'Male', 'Economically Disadvantaged', 'Special Education', 'Talented and Gifted', 'English Language Learner'], usecols=[0,1,2,3,4,5,6,7,8,9,10,11,12,13], header=None)
growth_1718_ela = pd.read_excel(sbac_growth_1718, sheetname = 'CCRdisaggbyschoolELASB', names=['school_id', 'school_name', 'All Students', 'Asian', 'Black', 'Hispanic/Latino', 'Multiracial', 'White', 'Female', 'Male', 'Economically Disadvantaged', 'Special Education', 'Talented and Gifted', 'English Language Learner'], usecols=[0,1,2,3,4,5,6,7,8,9,10,11,12,13], header=None)

part_rates = pd.read_excel(parti_rates, names=['school_id', 'school_name', 'grade', 'part_rate'], usecols=[0,1,2,7])

missing_fewer = pd.read_excel(attendance, names=['school_id', 'school_name', '12-13', '13-14', '14-15', '15-16', '16-17', '17-18'], usecols=[0,1,3,4,5,6,7,8], header=None)

disc_std_count = pd.read_excel(equ_crt, sheetname = 'DisciplineStudents', names=['school_id', 'school_name', '12-13', '13-14', '14-15', '15-16', '16-17', '17-18'], usecols=[0,1,2,3,4,5,6,7], header=None)
disc_class_days = pd.read_excel(equ_crt, sheetname = 'ClassDays', index_col=None, names=['school_id', 'school_name', '12-13', '13-14', '14-15', '15-16', '16-17', '17-18'], usecols=[0,1,2,3,4,5,6,7], header=None)
std_adult_cares = pd.read_excel(equ_crt, sheetname = 'SE_AdultCares', index_col=None, names=['school_id', 'school_name', '12-13', '13-14', '14-15', '15-16', '16-17', '17-18'], usecols=[0,1,3,4,5,6,7,8], header=None, na_filter=False)

parents_six_measures = pd.read_excel(six_measures, sheetname= 'Informed and valued', names=['school_id', 'school_name', '12-13', '13-14', '14-15', '15-16', '16-17', '17-18'], usecols=[0,1,2,3,4,5,6,7], header=None)

staff_voice = pd.read_excel(staff, names=['school_id', 'school_name', '14-15', '15-16', '16-17', '17-18'], usecols=[0,1,7,11,15,16], header=None)

In [9]:
principal_data['cost_center'] = principal_data['cost_center'].astype(str)

In [10]:
##### cost centers match to school code
def cost_center_to_school_id( cost ):
    if cost.startswith('1'):
        if cost == '113':
            return 1153
        elif cost == '116':
            return 1154
        elif cost == '119':
            return 1155
        elif cost == '122':
            return 1156
        elif cost == '124':
            return 4712
        elif cost == '127':
            return 3437
        elif cost == '131':
            return 1158
        elif cost == '134':
            return 1157
        elif cost == '137':
            return 1159
        elif cost == '139':
            return 5382
        elif cost == '141':
            return 1160
        elif cost == '143':
            return 1162
        elif cost == '144':
            return 1370
        elif cost == '146':
            return 1163
        elif cost == '151':
            return 1161
        elif cost == '152':
            return 1164
        elif cost == '154':
            return 4671
        elif cost == '157':
            return 1168
        elif cost == '161':
            return 1169
        elif cost == '164':
            return 2781
        elif cost == '165':
            return 1165
        elif cost == '167':
            return 1170
        elif cost == '169':
            return 1303
        elif cost == '171':
            return 1171
        elif cost == '174':
            return 1172
        elif cost == '176':
            return 1173
        elif cost == '177':
            return 1175
        elif cost == '179':
            return 1174
        elif cost == '182':
            return 1270
        elif cost == '185':
            return 1176
        elif cost == '186':
            return 1166
        elif cost == '188':
            return 1177
        elif cost == '191':
            return 1178
        elif cost == '194':
            return 1179
        else:
            return 'Not found'
    elif cost.startswith('3'):
        if cost == '321':
            return 1180
        elif cost == '323/423':
            return 1304
        elif cost == '326':
            return 1319
        elif cost == '331':
            return 1184
        elif cost == '341':
            return 1182
        elif cost == '346':
            return 2782
        elif cost == '351':
            return 1183
        elif cost == '357':
            return 1181
        elif cost == '361':
            return 1185
        elif cost == '371/471': 
            return 4474
        elif cost == '372/472':
            return 4638
        else:
            return 'Not found'
    elif cost.startswith('4'):
        if cost == '420':
            return 1186
        elif cost == '422':
            return 1305
        elif cost == '430':
            return 2783
        elif cost == '440':
            return 5381
        elif cost == '450':
            return 1187
        elif cost == '453':
            return 1314
        elif cost == '460':
            return 1320
        elif cost == '480':
            return 1188
        else:
            return 'Not found'
    else:
        return 'Not found'
             
principal_data['school_id'] = principal_data.cost_center.apply(cost_center_to_school_id)

In [11]:
principal_data.head()

,cost_center,school_name,principal,yrs_in_current_position,yrs_as_principal,total_district_yrs,employee_master_screen,school_id
0,420,Aloha High,Matt Casteel,1.0,10.0,20.0,NaN,1186
1,113,Aloha Huber Park K-8,Scott Drue,12.0,12.0,13.0,NaN,1153
2,323/423,Arts & Communication Magnet Academy,Bjorn Paige,2.0,2.0,2.0,NaN,1304
3,116,Barnes Elementary,Paul Marietta,2.0,2.0,2.0,NaN,1154
4,119,Beaver Acres Elementary,Stacy Geale,12.0,12.0,28.0,NaN,1155

In [12]:
#school name
school_name = principal_data[(principal_data.school_id == school)]['school_name'].iloc[0]
print( school_name)

Cooper Mountain Elementary

In [13]:
#principal data
principal_name = principal_data[(principal_data['school_id'] == school)]['principal'].iloc[0]
yrs_at_school = principal_data[(principal_data['school_id'] == school)]['yrs_as_principal'].iloc[0]
yrs_in_district = principal_data[(principal_data['school_id'] == school)]['total_district_yrs'].iloc[0]

In [14]:
#principal output
principal_output = []
principal_output.append(['School name:', school_name])
principal_output.append(['Principal name', principal_name])
principal_output.append(['Years as School Principal', yrs_at_school])
principal_output.append(['Years in BSD:', yrs_in_district])

In [15]:
principal_output

[['School name:', 'Cooper Mountain Elementary'],
 ['Principal name', 'Kristin LeMon'],
 ['Years as School Principal', 4.0],
 ['Years in BSD:', 36.0]]

In [16]:
ode_rc.head()

,school_id,grade_level,enrollment,latino,white,black,asian,pacific_islander,multiracial,native_american,swd,econdis,everell,languages_spoken
0,2243,Tot,40495.0,9991.0,19372.0,1217.0,6428.0,298.0,3039.0,150.0,4947.0,14097.0,10843.0,88.0
1,2243,K-3,12233.0,3017.0,5674.0,339.0,2135.0,74.0,947.0,47.0,1372.0,4142.0,3071.0,75.0
2,2243,2018-04-05 00:00:00,6466.0,1620.0,3031.0,191.0,1064.0,37.0,503.0,20.0,853.0,2378.0,1740.0,68.0
3,2243,2018-06-08 00:00:00,9613.0,2431.0,4536.0,269.0,1500.0,77.0,761.0,39.0,1173.0,3427.0,2630.0,73.0
4,2243,2018-09-12 00:00:00,12183.0,2923.0,6131.0,418.0,1729.0,110.0,828.0,44.0,1549.0,4150.0,3402.0,78.0

In [17]:
#drop header row
#ode_rc.drop(ode_rc.index[:1], inplace=True)
std_adult_cares.drop(std_adult_cares.index[:20], inplace=True)

In [18]:
#change columns to numeric
column_list = ['school_id', 'enrollment','languages_spoken']

for col in column_list:
   ode_rc[col] = ode_rc[col].apply(pd.to_numeric, errors='coerce')

In [19]:
# #ODE report card categories
def ode_data(category):
    val =  ode_rc[(ode_rc.school_id == school)][category].iloc[0]
    return val

In [20]:
ode_output = []
ode_output.append(['Enrollment:', ode_data('enrollment')])
ode_output.append(['Economically Disadvantaged:', ode_data('econdis')])
ode_output.append(['Students with Disabilities:', ode_data('swd')])
ode_output.append(['Ever English Language Learners:', ode_data('everell')])
ode_output.append(['Different Languages Spoken:', ode_data('languages_spoken')])
ode_output.append(['Native American:', ode_data('native_american')])
ode_output.append(['Asian', ode_data('asian')])
ode_output.append(['Black:', ode_data('black')])
ode_output.append(['Latino:', ode_data('latino')])
ode_output.append(['Multiracial:', ode_data('multiracial')])
ode_output.append(['Pacific Isl.:', ode_data('pacific_islander')])
ode_output.append(['White:', ode_data('white')])

In [85]:
# kindy_1718.head(6)

In [21]:
# drop rows
# kindy_1718.drop(kindy_1718.index[:5])
kindy_1617.drop(kindy_1617.index[:3], inplace=True)
kindy_1516.drop(kindy_1516.index[:4], inplace=True)
kindy_1415.drop(kindy_1415.index[:5], inplace=True)
# convert numeric columns to numbers

In [22]:
#change to numeric
column_list = ['app_to_learning_denom', 'num_and_ops_denom','letter_names_denom','letter_sounds_denom']

for col in column_list:
 #   kindy_1718[col] = kindy_1718[col].apply(pd.to_numeric, errors='coerce')
    kindy_1617[col] = kindy_1617[col].apply(pd.to_numeric, errors='coerce')
    kindy_1516[col] = kindy_1516[col].apply(pd.to_numeric, errors='coerce')
    kindy_1415[col] = kindy_1415[col].apply(pd.to_numeric, errors='coerce')

In [23]:
# restrict OKA to performance denominator >= 20
kindy_1617_ln = kindy_1617[(kindy_1617.letter_names_denom >= 20)]
kindy_1516_ln = kindy_1516[(kindy_1516.letter_names_denom >= 20)]
#kindy_1718_ln = kindy_1718[(kindy_1718.letter_names_denom >= 20)]

kindy_1617_ls = kindy_1617[(kindy_1617.letter_sounds_denom >= 20)]
kindy_1516_ls = kindy_1516[(kindy_1516.letter_sounds_denom >= 20)]
#kindy_1718_ls = kindy_1718[(kindy_1718.letter_sounds_denom >= 20)]

kindy_1617_em = kindy_1617[(kindy_1617.num_and_ops_denom >= 20)]
kindy_1516_em = kindy_1516[(kindy_1516.num_and_ops_denom >= 20)]
#kindy_1718_em = kindy_1718[(kindy_1718.num_and_ops_denom >= 20)]

kindy_1617_al = kindy_1617[(kindy_1617.app_to_learning_denom >= 20)]
kindy_1516_al = kindy_1516[(kindy_1516.app_to_learning_denom >= 20)]
#kindy_1718_al = kindy_1718[(kindy_1718.app_to_learning_denom >= 20)]

In [113]:
#round to 1 decimal
#kindy_1718_ln.round(1)

In [24]:
#OKA variables: letter names, letter sounds, early mathematics, approaches to learning
def kindy_letter_names(year, school, s_group):
    if year == 1718:
        if s_group == 'All Students':
            val =  kindy_1718_ln[(kindy_1718_ln.school_id == school) & (kindy_1718_ln.student_group == 'Total Population')]['letter_names']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1718_ln[(kindy_1718_ln.school_id == school) & (kindy_1718_ln.student_group == 'Economically Dis')]['letter_names']
        elif s_group == 'English Language Learners':
            val =  kindy_1718_ln[(kindy_1718_ln.school_id == school) & (kindy_1718_ln.student_group == 'Limited English ')]['letter_names']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1718_ln[(kindy_1718_ln.school_id == school) & (kindy_1718_ln.student_group == 'Students with Di')]['letter_names']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    elif year == 1617:
        if s_group == 'All Students':
            val =  kindy_1617_ln[(kindy_1617_ln.school_id == school) & (kindy_1617_ln.student_group == 'Total Population')]['letter_names']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1617_ln[(kindy_1617_ln.school_id == school) & (kindy_1617_ln.student_group == 'Economically Dis')]['letter_names']
        elif s_group == 'English Language Learners':
            val =  kindy_1617_ln[(kindy_1617_ln.school_id == school) & (kindy_1617_ln.student_group == 'Limited English ')]['letter_names']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1617_ln[(kindy_1617_ln.school_id == school) & (kindy_1617_ln.student_group == 'Students with Di')]['letter_names']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    elif year == 1516:
        if s_group == 'All Students':
            val =  kindy_1516_ln[(kindy_1516_ln.school_id == school) & (kindy_1516_ln.student_group == 'Total Population')]['letter_names']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1516_ln[(kindy_1516_ln.school_id == school) & (kindy_1516_ln.student_group == 'Economically Disadvantaged')]['letter_names']
        elif s_group == 'English Language Learners':
            val =  kindy_1516_ln[(kindy_1516_ln.school_id == school) & (kindy_1516_ln.student_group == 'Limited English Proficient')]['letter_names']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1516_ln[(kindy_1516_ln.school_id == school) & (kindy_1516_ln.student_group == 'Students with Disabilities')]['letter_names']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    elif year == 1415:
        if s_group == 'All Students':
            val =  kindy_1415_ln[(kindy_1415_ln.school_id == school) & (kindy_1415_ln.student_group == 'Total Population')]['letter_names']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1415_ln[(kindy_1415_ln.school_id == school) & (kindy_1415_ln.student_group == 'Economically Disadvantaged')]['letter_names']
        elif s_group == 'English Language Learners':
            val =  kindy_1415_ln[(kindy_1415_ln.school_id == school) & (kindy_1415_ln.student_group == 'Limited English Proficient')]['letter_names']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1415_ln[(kindy_1415_ln.school_id == school) & (kindy_1415_ln.student_group == 'Students with Disabilities')]['letter_names']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    else: 
        print("Year must be 1415, 1516, 1617, or 1718")
    if len(val) > 0:
        return '{0:.1f}'.format( round(val.iloc[0], 1) )
    else:
        return ''
        
def kindy_letter_sounds(year, school, s_group):
    if year == 1718:
        if s_group == 'All Students':
            val =  kindy_1718_ls[(kindy_1718_ls.school_id == school) & (kindy_1718_ls.student_group == 'Total Population')]['letter_sounds']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1718_ls[(kindy_1718_ls.school_id == school) & (kindy_1718_ls.student_group == 'Economically Dis')]['letter_sounds']
        elif s_group == 'English Language Learners':
            val =  kindy_1718_ls[(kindy_1718_ls.school_id == school) & (kindy_1718_ls.student_group == 'Limited English ')]['letter_sounds']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1718_ls[(kindy_1718_ls.school_id == school) & (kindy_1718_ls.student_group == 'Students with Di')]['letter_sounds']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    elif year == 1617:
        if s_group == 'All Students':
            val =  kindy_1617_ls[(kindy_1617_ls.school_id == school) & (kindy_1617_ls.student_group == 'Total Population')]['letter_sounds']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1617_ls[(kindy_1617_ls.school_id == school) & (kindy_1617_ls.student_group == 'Economically Dis')]['letter_sounds']
        elif s_group == 'English Language Learners':
            val =  kindy_1617_ls[(kindy_1617_ls.school_id == school) & (kindy_1617_ls.student_group == 'Limited English ')]['letter_sounds']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1617_ls[(kindy_1617_ls.school_id == school) & (kindy_1617_ls.student_group == 'Students with Di')]['letter_sounds']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    elif year == 1516:
        if s_group == 'All Students':
            val =  kindy_1516_ls[(kindy_1516_ls.school_id == school) & (kindy_1516_ls.student_group == 'Total Population')]['letter_sounds']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1516_ls[(kindy_1516_ls.school_id == school) & (kindy_1516_ls.student_group == 'Economically Disadvantaged')]['letter_sounds']
        elif s_group == 'English Language Learners':
            val =  kindy_1516_ls[(kindy_1516_ls.school_id == school) & (kindy_1516_ls.student_group == 'Limited English Proficient')]['letter_sounds']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1516_ls[(kindy_1516_ls.school_id == school) & (kindy_1516_ls.student_group == 'Students with Disabilities')]['letter_sounds']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    elif year == 1415:
        if s_group == 'All Students':
            val =  kindy_1415_ls[(kindy_1415_ls.school_id == school) & (kindy_1415_ls.student_group == 'Total Population')]['letter_sounds']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1415_ls[(kindy_1415_ls.school_id == school) & (kindy_1415_ls.student_group == 'Economically Disadvantaged')]['letter_sounds']
        elif s_group == 'English Language Learners':
            val =  kindy_1415_ls[(kindy_1415_ls.school_id == school) & (kindy_1415_ls.student_group == 'Limited English Proficient')]['letter_sounds']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1415_ls[(kindy_1415_ls.school_id == school) & (kindy_1415_ls.student_group == 'Students with Disabilities')]['letter_sounds']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    else: 
        print("Year must be 1415, 1516, or 1617")
    if len(val) > 0:
        return '{0:.1f}'.format( round(val.iloc[0], 1) )
    else:
        return ''
        
def kindy_num_and_ops(year, school, s_group):
    if year == 1718:
        if s_group == 'All Students':
            val =  kindy_1718_em[(kindy_1718_em.school_id == school) & (kindy_1718_em.student_group == 'Total Population')]['num_and_ops']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1718_em[(kindy_1718_em.school_id == school) & (kindy_1718_em.student_group == 'Economically Dis')]['num_and_ops']
        elif s_group == 'English Language Learners':
            val =  kindy_1718_em[(kindy_1718_em.school_id == school) & (kindy_1718_em.student_group == 'Limited English ')]['num_and_ops']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1718_em[(kindy_1718_em.school_id == school) & (kindy_1718_em.student_group == 'Students with Disabilities')]['num_and_ops']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    elif year == 1617:
        if s_group == 'All Students':
            val =  kindy_1617_em[(kindy_1617_em.school_id == school) & (kindy_1617_em.student_group == 'Total Population')]['num_and_ops']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1617_em[(kindy_1617_em.school_id == school) & (kindy_1617_em.student_group == 'Economically Dis')]['num_and_ops']
        elif s_group == 'English Language Learners':
            val =  kindy_1617_em[(kindy_1617_em.school_id == school) & (kindy_1617_em.student_group == 'Limited English ')]['num_and_ops']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1617_em[(kindy_1617_em.school_id == school) & (kindy_1617_em.student_group == 'Students with Disabilities')]['num_and_ops']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    elif year == 1516:
        if s_group == 'All Students':
            val =  kindy_1516_em[(kindy_1516_em.school_id == school) & (kindy_1516_em.student_group == 'Total Population')]['num_and_ops']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1516_em[(kindy_1516_em.school_id == school) & (kindy_1516_em.student_group == 'Economically Disadvantaged')]['num_and_ops']
        elif s_group == 'English Language Learners':
            val =  kindy_1516_em[(kindy_1516_em.school_id == school) & (kindy_1516_em.student_group == 'Limited English Proficient')]['num_and_ops']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1516_em[(kindy_1516_em.school_id == school) & (kindy_1516_em.student_group == 'Students with Di')]['num_and_ops']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    elif year == 1415:
        if s_group == 'All Students':
            val =  kindy_1415_em[(kindy_1415_em.school_id == school) & (kindy_1415_em.student_group == 'Total Population')]['num_and_ops']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1415_em[(kindy_1415_em.school_id == school) & (kindy_1415_em.student_group == 'Economically Disadvantaged')]['num_and_ops']
        elif s_group == 'English Language Learners':
            val =  kindy_1415_em[(kindy_1415_em.school_id == school) & (kindy_1415_em.student_group == 'Limited English Proficient')]['num_and_ops']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1415_em[(kindy_1415_em.school_id == school) & (kindy_1415_em.student_group == 'Students with Disabilities')]['num_and_ops']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    else: 
        print("Year must be 1415, 1516, or 1617")
    if len(val) > 0:
        return '{0:.1f}'.format( round(val.iloc[0], 1) )
    else:
        return ''
        
def kindy_app_to_learning(year, school, s_group):
    if year == 1718:
        if s_group == 'All Students':
            val =  kindy_1617_al[(kindy_1617_al.school_id == school) & (kindy_1718_al.student_group == 'Total Population')]['app_to_learning']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1718_al[(kindy_1718_al.school_id == school) & (kindy_1718_al.student_group == 'Economically Dis')]['app_to_learning']
        elif s_group == 'English Language Learners':
            val =  kindy_1718_al[(kindy_1718_al.school_id == school) & (kindy_1718_al.student_group == 'Limited English ')]['app_to_learning']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1718_al[(kindy_1718_al.school_id == school) & (kindy_1718_al.student_group == 'Students with Di')]['app_to_learning']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    elif year == 1617:
        if s_group == 'All Students':
            val =  kindy_1617_al[(kindy_1617_al.school_id == school) & (kindy_1617_al.student_group == 'Total Population')]['app_to_learning']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1617_al[(kindy_1617_al.school_id == school) & (kindy_1617_al.student_group == 'Economically Dis')]['app_to_learning']
        elif s_group == 'English Language Learners':
            val =  kindy_1617_al[(kindy_1617_al.school_id == school) & (kindy_1617_al.student_group == 'Limited English ')]['app_to_learning']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1617_al[(kindy_1617_al.school_id == school) & (kindy_1617_al.student_group == 'Students with Di')]['app_to_learning']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    elif year == 1516:
        if s_group == 'All Students':
            val =  kindy_1516_al[(kindy_1516_al.school_id == school) & (kindy_1516_al.student_group == 'Total Population')]['app_to_learning']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1516_al[(kindy_1516_al.school_id == school) & (kindy_1516_al.student_group == 'Economically Disadvantaged')]['app_to_learning']
        elif s_group == 'English Language Learners':
            val =  kindy_1516_al[(kindy_1516_al.school_id == school) & (kindy_1516_al.student_group == 'Limited English Proficient')]['app_to_learning']
        elif s_group == 'Students with Disabilities':
            val =  kindy_1516_al[(kindy_1516_al.school_id == school) & (kindy_1516_al.student_group == 'Students with Disabilities')]['app_to_learning']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    elif year == 1415:
        if s_group == 'All Students':
            val =  kindy_1415_al[(kindy_1415_al.school_id == school) & (kindy_1415_al.student_group == 'Total Population')]['app_to_learning']
        elif s_group == 'Economically Disadvantaged':
            val =  kindy_1415_al[(kindy_1415_al.school_id == school) & (kindy_1415_al.student_group == 'Economically Disadvantaged')]['app_to_learning']
        elif s_group == 'English Language Learners':
            val =  kindy_1415_al[(kindy_1415_al.school_id == school) & (kindy_1415_al.student_group == 'Limited English Proficient')]['app_to_learning']
        elif s_group == 'Students with Disabilities':
            val = kindy_1415_al[(kindy_1415_al.school_id == school) & (kindy_1415_al.student_group == 'Students with Disabilities')]['app_to_learning']
        else:
            print("Student group should match categories in SIP: All Students, Economically Disadvantaged, English Language Learners, or Students with Disabilities")
    else: 
        print("Year must be 1415, 1516, or 1617")
    if len(val) > 0:
        return '{0:.1f}'.format( round(val.iloc[0], 1) )
    else:
        return ''

In [115]:
#kindy_1718_ln.iloc[52]

In [25]:
# OKA letter names
#1516
oka_1516_ln_total = kindy_letter_names(1516, school, 'All Students')
oka_1516_ln_ed = kindy_letter_names(1516, school, 'Economically Disadvantaged')
oka_1516_ln_ell = kindy_letter_names(1516, school, 'English Language Learners')
oka_1516_ln_swd = kindy_letter_names(1516, school, 'Students with Disabilities')
#1617
oka_1617_ln_total = kindy_letter_names(1617, school, 'All Students')
oka_1617_ln_ed = kindy_letter_names(1617, school, 'Economically Disadvantaged')
oka_1617_ln_ell = kindy_letter_names(1617, school, 'English Language Learners')
oka_1617_ln_swd = kindy_letter_names(1617, school, 'Students with Disabilities')
#1718
# oka_1718_ln_total = kindy_letter_names(1718, school, 'All Students')
# oka_1718_ln_ed = kindy_letter_names(1718, school, 'Economically Disadvantaged')
# oka_1718_ln_ell = kindy_letter_names(1718, school, 'English Language Learners')
# oka_1718_ln_swd = kindy_letter_names(1718, school, 'Students with Disabilities')

#OKA Letter sounds
#1516
oka_1516_ls_total = kindy_letter_sounds(1516, school, 'All Students')
oka_1516_ls_ed = kindy_letter_sounds(1516, school, 'Economically Disadvantaged')
oka_1516_ls_ell = kindy_letter_sounds(1516, school, 'English Language Learners')
oka_1516_ls_swd = kindy_letter_sounds(1516, school, 'Students with Disabilities')
#1617
oka_1617_ls_total = kindy_letter_sounds(1617, school, 'All Students')
oka_1617_ls_ed = kindy_letter_sounds(1617, school, 'Economically Disadvantaged')
oka_1617_ls_ell = kindy_letter_sounds(1617, school, 'English Language Learners')
oka_1617_ls_swd = kindy_letter_sounds(1617, school, 'Students with Disabilities')
#1718
# oka_1718_ls_total = kindy_letter_sounds(1718, school, 'All Students')
# oka_1718_ls_ed = kindy_letter_sounds(1718, school, 'Economically Disadvantaged')
# oka_1718_ls_ell = kindy_letter_sounds(1718, school, 'English Language Learners')
# oka_1718_ls_swd = kindy_letter_sounds(1718, school, 'Students with Disabilities')

#OKA Early math
#1516
oka_1516_em_total = kindy_num_and_ops(1516, school, 'All Students')
oka_1516_em_ed = kindy_num_and_ops(1516, school, 'Economically Disadvantaged')
oka_1516_em_ell = kindy_num_and_ops(1516, school, 'English Language Learners')
oka_1516_em_swd = kindy_num_and_ops(1516, school, 'Students with Disabilities')
#1617
oka_1617_em_total = kindy_num_and_ops(1617, school, 'All Students')
oka_1617_em_ed = kindy_num_and_ops(1617, school, 'Economically Disadvantaged')
oka_1617_em_ell = kindy_num_and_ops(1617, school, 'English Language Learners')
oka_1617_em_swd = kindy_num_and_ops(1617, school, 'Students with Disabilities')
#1718
# oka_1718_em_total = kindy_num_and_ops(1718, school, 'All Students')
# oka_1718_em_ed = kindy_num_and_ops(1718, school, 'Economically Disadvantaged')
# oka_1718_em_ell = kindy_num_and_ops(1718, school, 'English Language Learners')
# oka_1718_em_swd = kindy_num_and_ops(1718, school, 'Students with Disabilities')

#OKA approaches to learning
#1516
oka_1516_al_total = kindy_app_to_learning(1516, school, 'All Students')
oka_1516_al_ed = kindy_app_to_learning(1516, school, 'Economically Disadvantaged')
oka_1516_al_ell = kindy_app_to_learning(1516, school, 'English Language Learners')
oka_1516_al_swd = kindy_app_to_learning(1516, school, 'Students with Disabilities')
#1617
oka_1617_al_total = kindy_app_to_learning(1617, school, 'All Students')
oka_1617_al_ed = kindy_app_to_learning(1617, school, 'Economically Disadvantaged')
oka_1617_al_ell = kindy_app_to_learning(1617, school, 'English Language Learners')
oka_1617_al_swd = kindy_app_to_learning(1617, school, 'Students with Disabilities')
#1718
# oka_1718_al_total = kindy_app_to_learning(1718, school, 'All Students')
# oka_1718_al_ed = kindy_app_to_learning(1718, school, 'Economically Disadvantaged')
# oka_1718_al_ell = kindy_app_to_learning(1718, school, 'English Language Learners')
# oka_1718_al_swd = kindy_app_to_learning(1718, school, 'Students with Disabilities')

In [117]:
# oka_output = []
# oka_output.append(['Letter Names', '15-16', '16-17', '17-18'])
# oka_output.append(['All Students', oka_1516_ln_total, oka_1617_ln_total, oka_1718_ln_total])
# oka_output.append(['Economically Disadvantaged', oka_1516_ln_ed, oka_1617_ln_ed, oka_1718_ln_ed])
# oka_output.append(['English Language Learners', oka_1516_ln_ell, oka_1617_ln_ell, oka_1718_ln_ell])
# oka_output.append(['Students with Disabilities', oka_1516_ln_swd, oka_1617_ln_swd, oka_1718_ln_swd])

# oka_output.append(['Letter Sounds', '15-16', '16-17', '17-18'])
# oka_output.append(['All Students', oka_1516_ls_total, oka_1617_ls_total, oka_1718_ls_total])
# oka_output.append(['Economically Disadvantaged', oka_1516_ls_ed, oka_1617_ls_ed, oka_1718_ls_ed])
# oka_output.append(['English Language Learners', oka_1516_ls_ell, oka_1617_ls_ell, oka_1718_ls_ell])
# oka_output.append(['Students with Disabilities', oka_1516_ls_swd, oka_1617_ls_swd, oka_1718_ls_swd])

# oka_output.append(['Early Mathematics', '15-16', '16-17', '17-18'])
# oka_output.append(['All Students', oka_1516_em_total, oka_1617_em_total, oka_1718_em_total])
# oka_output.append(['Economically Disadvantaged', oka_1516_em_ed, oka_1617_em_ed, oka_1718_em_ed])
# oka_output.append(['English Language Learners', oka_1516_em_ell, oka_1617_em_ell, oka_1718_em_ell])
# oka_output.append(['Students with Disabilities', oka_1516_em_swd, oka_1617_em_swd, oka_1718_em_swd])

# oka_output.append(['Approaches to Learning', '15-16', '16-17', '17-18'])
# oka_output.append(['All Students', oka_1516_al_total, oka_1617_al_total, oka_1718_al_total])
# oka_output.append(['Economically Disadvantaged', oka_1516_al_ed, oka_1617_al_ed, oka_1718_al_ed])
# oka_output.append(['English Language Learners', oka_1516_al_ell, oka_1617_al_ell, oka_1718_al_ell])
# oka_output.append(['Students with Disabilities', oka_1516_al_swd, oka_1617_al_swd, oka_1718_al_swd])

In [26]:
#temp - no 1718 
oka_output = []
oka_output.append(['Letter Names', '15-16', '16-17', '17-18'])
oka_output.append(['All Students', oka_1516_ln_total, oka_1617_ln_total, 'N/A'])
oka_output.append(['Economically Disadvantaged', oka_1516_ln_ed, oka_1617_ln_ed, 'N/A'])
oka_output.append(['English Language Learners', oka_1516_ln_ell, oka_1617_ln_ell, 'N/A'])
oka_output.append(['Students with Disabilities', oka_1516_ln_swd, oka_1617_ln_swd, 'N/A'])

oka_output.append(['Letter Sounds', '15-16', '16-17', '17-18'])
oka_output.append(['All Students', oka_1516_ls_total, oka_1617_ls_total, 'N/A'])
oka_output.append(['Economically Disadvantaged', oka_1516_ls_ed, oka_1617_ls_ed, 'N/A'])
oka_output.append(['English Language Learners', oka_1516_ls_ell, oka_1617_ls_ell, 'N/A'])
oka_output.append(['Students with Disabilities', oka_1516_ls_swd, oka_1617_ls_swd, 'N/A'])

oka_output.append(['Early Mathematics', '15-16', '16-17', '17-18'])
oka_output.append(['All Students', oka_1516_em_total, oka_1617_em_total, 'N/A'])
oka_output.append(['Economically Disadvantaged', oka_1516_em_ed, oka_1617_em_ed, 'N/A'])
oka_output.append(['English Language Learners', oka_1516_em_ell, oka_1617_em_ell, 'N/A'])
oka_output.append(['Students with Disabilities', oka_1516_em_swd, oka_1617_em_swd, 'N/A'])

oka_output.append(['Approaches to Learning', '15-16', '16-17', '17-18'])
oka_output.append(['All Students', oka_1516_al_total, oka_1617_al_total, 'N/A'])
oka_output.append(['Economically Disadvantaged', oka_1516_al_ed, oka_1617_al_ed, 'N/A'])
oka_output.append(['English Language Learners', oka_1516_al_ell, oka_1617_al_ell, 'N/A'])
oka_output.append(['Students with Disabilities', oka_1516_al_swd, oka_1617_al_swd, 'N/A'])

In [45]:
sbac_1718_both = pd.read_excel(sbac_1718, index_col=None, names=['school_id', 'grade_group', 'school_name', 'student_group', 'ela1718partirate', 'ela1718perfdenom', 'ela_pct_met', 'ela1718mgp', 'math1718partirate', 'math1718perfdenom', 'math_pct_met', 'math1718mgp'])

In [46]:
# restrict to performance denominator >= 20
sbac_1415_ela = sbac_1415_ela[(sbac_1415_ela.performance_denominator >= 20)]
sbac_1415_math = sbac_1415_math[(sbac_1415_math.performance_denominator >= 20)]

sbac_1516_ela = sbac_1516_ela[(sbac_1516_ela.performance_denominator >= 20)]
sbac_1516_math = sbac_1516_math[(sbac_1516_math.performance_denominator >= 20)]

sbac_1617_ela = sbac_1617_ela[(sbac_1617_ela.performance_denominator >= 20)]
sbac_1617_math = sbac_1617_math[(sbac_1617_math.performance_denominator >= 20)]

sbac_1718_ela = sbac_1718_both[(sbac_1718_both.ela1718perfdenom >= 20)]
sbac_1718_math = sbac_1718_both[(sbac_1718_both.math1718perfdenom >= 20)]

In [47]:
#change to percent
sbac_1415_ela['percent_met_round'] = sbac_1415_ela['percent_met'].apply(lambda x: '{0:.0f}%'.format(x))
sbac_1415_math['percent_met_round'] = sbac_1415_math['percent_met'].apply(lambda x: '{0:.0f}%'.format(x))
sbac_1516_ela['percent_met_round'] = sbac_1516_ela['percent_met'].apply(lambda x: '{0:.0f}%'.format(x*100))
sbac_1516_math['percent_met_round'] = sbac_1516_math['percent_met'].apply(lambda x: '{0:.0f}%'.format(x*100))
sbac_1617_ela['percent_met_round'] = sbac_1617_ela['percent_met'].apply(lambda x: '{0:.0f}%'.format(x))
sbac_1617_math['percent_met_round'] = sbac_1617_math['percent_met'].apply(lambda x: '{0:.0f}%'.format(x))
sbac_1718_ela['percent_met_round'] = sbac_1718_ela['ela_pct_met'].apply(lambda x: '{0:.0f}%'.format(x))
sbac_1718_math['percent_met_round'] = sbac_1718_math['math_pct_met'].apply(lambda x: '{0:.0f}%'.format(x))

In [48]:
def sbac(year, subject, school, grade, s_group):
    if year == 1415: 
        if subject.lower() == 'ela': 
            val = sbac_1415_ela[(sbac_1415_ela.school_id == school) & (sbac_1415_ela.grade_group == grade) & (sbac_1415_ela.student_group == s_group)]['percent_met_round']
            if len(val) > 0:
                if sbac_1415_ela[(sbac_1415_ela.school_id == school) & (sbac_1415_ela.grade_group == grade) & (sbac_1415_ela.student_group == s_group)]['percent_met'].iloc[0] > 95:
                    return '>95%'
                elif sbac_1415_ela[(sbac_1415_ela.school_id == school) & (sbac_1415_ela.grade_group == grade) & (sbac_1415_ela.student_group == s_group)]['percent_met'].iloc[0] < 5:
                    return '<5%'
                else:
                    return val.iloc[0]
            else:
                return ''
        elif subject.lower() == 'math':
            val = sbac_1415_math[(sbac_1415_math.school_id == school) & (sbac_1415_math.grade_group == grade) & (sbac_1415_math.student_group == s_group)]['percent_met_round']
            if len(val) > 0:
                if sbac_1415_math[(sbac_1415_math.school_id == school) & (sbac_1415_math.grade_group == grade) & (sbac_1415_math.student_group == s_group)]['percent_met'].iloc[0] > 95:
                    return '>95%'
                elif sbac_1415_math[(sbac_1415_math.school_id == school) & (sbac_1415_math.grade_group == grade) & (sbac_1415_math.student_group == s_group)]['percent_met'].iloc[0] < 5:
                    return '<5%'
                else:
                        return val.iloc[0]
            else:
                return ''
        else:
            print("Subject must be math or ela")

    elif year == 1516:
        if subject.lower() == 'ela': 
            val = sbac_1516_ela[(sbac_1516_ela.school_id == school) & (sbac_1516_ela.grade_group == grade) & (sbac_1516_ela.student_group == s_group)]['percent_met_round']
            if len(val) > 0:
                if sbac_1516_ela[(sbac_1516_ela.school_id == school) & (sbac_1516_ela.grade_group == grade) & (sbac_1516_ela.student_group == s_group)]['percent_met'].iloc[0] > .95:
                    return '>95%'
                elif sbac_1516_ela[(sbac_1516_ela.school_id == school) & (sbac_1516_ela.grade_group == grade) & (sbac_1516_ela.student_group == s_group)]['percent_met'].iloc[0] < .05:
                    return '<5%'
                else:
                    return val.iloc[0]
            else:
                return ''
        elif subject.lower() == 'math':
            val = sbac_1516_math[(sbac_1516_math.school_id == school) & (sbac_1516_math.grade_group == grade) & (sbac_1516_math.student_group == s_group)]['percent_met_round']
            if len(val) > 0:
                if sbac_1516_math[(sbac_1516_math.school_id == school) & (sbac_1516_math.grade_group == grade) & (sbac_1516_math.student_group == s_group)]['percent_met'].iloc[0] > .95:
                    return '>95%'
                elif sbac_1516_math[(sbac_1516_math.school_id == school) & (sbac_1516_math.grade_group == grade) & (sbac_1516_math.student_group == s_group)]['percent_met'].iloc[0] < .05:
                    return '<5%'
                else:
                    return val.iloc[0]
            else:
                return ''
        else:
            print("Subject must be math or ela")
    elif year == 1617:
        if subject.lower() == 'ela': 
            val = sbac_1617_ela[(sbac_1617_ela.school_id == school) & (sbac_1617_ela.grade_group == grade) & (sbac_1617_ela.student_group == s_group)]['percent_met_round']
            if len(val) > 0:
                if sbac_1617_ela[(sbac_1617_ela.school_id == school) & (sbac_1617_ela.grade_group == grade) & (sbac_1617_ela.student_group == s_group)]['percent_met'].iloc[0] > 95:
                    return '>95%'
                elif sbac_1617_ela[(sbac_1617_ela.school_id == school) & (sbac_1617_ela.grade_group == grade) & (sbac_1617_ela.student_group == s_group)]['percent_met'].iloc[0] < 5:
                    return '<5%'
                else:
                    return val.iloc[0]
            else:
                return ''
        elif subject.lower() == 'math':
            val = sbac_1617_math[(sbac_1617_math.school_id == school) & (sbac_1617_math.grade_group == grade) & (sbac_1617_math.student_group == s_group)]['percent_met_round']
            if len(val) > 0:
                if sbac_1617_math[(sbac_1617_math.school_id == school) & (sbac_1617_math.grade_group == grade) & (sbac_1617_math.student_group == s_group)]['percent_met'].iloc[0] > 95:
                    return '>95%'
                elif sbac_1617_math[(sbac_1617_math.school_id == school) & (sbac_1617_math.grade_group == grade) & (sbac_1617_math.student_group == s_group)]['percent_met'].iloc[0] < 5:
                    return '<5%'
                else:
                    return val.iloc[0]
            else:
                return ''
        else:
            print("Subject must be math or ela")    
    elif year == 1718:
        if subject.lower() == 'ela': 
            val = sbac_1718_ela[(sbac_1718_ela.school_id == school) & (sbac_1718_ela.grade_group == grade) & (sbac_1718_ela.student_group == s_group)]['percent_met_round']
            if len(val) > 0:
                if sbac_1718_ela[(sbac_1718_ela.school_id == school) & (sbac_1718_ela.grade_group == grade) & (sbac_1718_ela.student_group == s_group)]['ela_pct_met'].iloc[0] > 95:
                    return '>95%'
                elif sbac_1718_ela[(sbac_1718_ela.school_id == school) & (sbac_1718_ela.grade_group == grade) & (sbac_1718_ela.student_group == s_group)]['ela_pct_met'].iloc[0] < 5:
                    return '<5%'
                else:
                    return val.iloc[0]
            else:
                return ''
        elif subject.lower() == 'math':
            val = sbac_1718_math[(sbac_1718_math.school_id == school) & (sbac_1718_math.grade_group == grade) & (sbac_1718_math.student_group == s_group)]['percent_met_round']
            if len(val) > 0:
                if sbac_1718_math[(sbac_1718_math.school_id == school) & (sbac_1718_math.grade_group == grade) & (sbac_1718_math.student_group == s_group)]['math_pct_met'].iloc[0] > 95:
                    return '>95%'
                elif sbac_1718_math[(sbac_1718_math.school_id == school) & (sbac_1718_math.grade_group == grade) & (sbac_1718_math.student_group == s_group)]['math_pct_met'].iloc[0] < 5:
                    return '<5%'
                else:
                    return val.iloc[0]
            else:
                return ''
        else:
            print("Subject must be math or ela") 
    else:
        print("Enter a school year as 1415, e.g.")

In [50]:
# SBAC: ELA grade 3
#14-15
ela_1415_gr3_total = sbac(1415, 'ela', school, 3, 'Total')
ela_1415_gr3_econdis = sbac(1415, 'ela', school, 3, 'Economically Disadvantaged')
ela_1415_gr3_ell = sbac(1415, 'ela', school, 3, 'Limited English Proficient')
ela_1415_gr3_ever_ell = sbac(1415, 'ela', school, 3, 'Ever Limited English Proficient')
ela_1415_gr3_SwD = sbac(1415, 'ela', school, 3, 'Students with Disabilities')
ela_1415_gr3_tag = sbac(1415, 'ela', school, 3, 'Talented and Gifted')
ela_1415_gr3_asian = sbac(1415, 'ela', school, 3, 'Asian')
ela_1415_gr3_hisp = sbac(1415, 'ela', school, 3, 'Hispanic/Latino')
ela_1415_gr3_white = sbac(1415, 'ela', school, 3, 'White')
ela_1415_gr3_multir = sbac(1415, 'ela', school, 3, 'Multi-Racial')
ela_1415_gr3_male = sbac(1415, 'ela', school, 3, 'Male')
ela_1415_gr3_female = sbac(1415, 'ela', school, 3, 'Female')
# #15-16
ela_1516_gr3_total = sbac(1516, 'ela', school, 3, 'Total')
ela_1516_gr3_econdis = sbac(1516, 'ela', school, 3, 'Economically Disadvantaged')
ela_1516_gr3_ell = sbac(1516, 'ela', school, 3, 'Limited English Proficient')
ela_1516_gr3_ever_ell = sbac(1516, 'ela', school, 3, 'Ever Limited English Proficient')
ela_1516_gr3_SwD = sbac(1516, 'ela', school, 3, 'Students with Disabilities')
ela_1516_gr3_tag = sbac(1516, 'ela', school, 3, 'Talented and Gifted')
ela_1516_gr3_asian = sbac(1516, 'ela', school, 3, 'Asian')
ela_1516_gr3_hisp = sbac(1516, 'ela', school, 3, 'Hispanic/Latino')
ela_1516_gr3_white = sbac(1516, 'ela', school, 3, 'White')
ela_1516_gr3_multir = sbac(1516, 'ela', school, 3, 'Multi-Racial')
ela_1516_gr3_male = sbac(1516, 'ela', school, 3, 'Male')
ela_1516_gr3_female = sbac(1516, 'ela', school, 3, 'Female')
# 16-17
ela_1617_gr3_total = sbac(1617, 'ela', school, 3, 'Total')
ela_1617_gr3_econdis = sbac(1617, 'ela', school, 3, 'Economically Disadvantaged')
ela_1617_gr3_ell = sbac(1617, 'ela', school, 3, 'Limited English Proficient')
ela_1617_gr3_ever_ell = sbac(1617, 'ela', school, 3, 'Ever Limited English Proficient')
ela_1617_gr3_SwD = sbac(1617, 'ela', school, 3, 'Students with Disabilities')
ela_1617_gr3_tag = sbac(1617, 'ela', school, 3, 'Talented and Gifted')
ela_1617_gr3_asian = sbac(1617, 'ela', school, 3, 'Asian')
ela_1617_gr3_hisp = sbac(1617, 'ela', school, 3, 'Hispanic/Latino')
ela_1617_gr3_white = sbac(1617, 'ela', school, 3, 'White')
ela_1617_gr3_multir = sbac(1617, 'ela', school, 3, 'Multi-Racial')
ela_1617_gr3_male = sbac(1617, 'ela', school, 3, 'Male')
ela_1617_gr3_female = sbac(1617, 'ela', school, 3, 'Female')

# 17-18
ela_1718_gr3_total = sbac(1718, 'ela', school, 3, 'Total')
ela_1718_gr3_econdis = sbac(1718, 'ela', school, 3, 'Economically Disadvantaged')
ela_1718_gr3_ell = sbac(1718, 'ela', school, 3, 'Limited English Proficient')
ela_1718_gr3_ever_ell = sbac(1718, 'ela', school, 3, 'Ever Limited English Proficient')
ela_1718_gr3_SwD = sbac(1718, 'ela', school, 3, 'Students with Disabilities')
ela_1718_gr3_tag = sbac(1718, 'ela', school, 3, 'Talented and Gifted')
ela_1718_gr3_asian = sbac(1718, 'ela', school, 3, 'Asian')
ela_1718_gr3_hisp = sbac(1718, 'ela', school, 3, 'Hispanic/Latino')
ela_1718_gr3_white = sbac(1718, 'ela', school, 3, 'White')
ela_1718_gr3_multir = sbac(1718, 'ela', school, 3, 'Multi-Racial')
ela_1718_gr3_male = sbac(1718, 'ela', school, 3, 'Male')
ela_1718_gr3_female = sbac(1718, 'ela', school, 3, 'Female')

#SBAC: ELA grade 5
#1415
ela_1415_gr5_total = sbac(1415, 'ela', school, 5, 'Total')
ela_1415_gr5_econdis = sbac(1415, 'ela', school, 5, 'Economically Disadvantaged')
ela_1415_gr5_ell = sbac(1415, 'ela', school, 5, 'Limited English Proficient')
ela_1415_gr5_ever_ell = sbac(1415, 'ela', school, 5, 'Ever Limited English Proficient')
ela_1415_gr5_SwD = sbac(1415, 'ela', school, 5, 'Students with Disabilities')
ela_1415_gr5_tag = sbac(1415, 'ela', school, 5, 'Talented and Gifted')
ela_1415_gr5_asian = sbac(1415, 'ela', school, 5, 'Asian')
ela_1415_gr5_hisp = sbac(1415, 'ela', school, 5, 'Hispanic/Latino')
ela_1415_gr5_white = sbac(1415, 'ela', school, 5, 'White')
ela_1415_gr5_multir = sbac(1415, 'ela', school, 5, 'Multi-Racial')
ela_1415_gr5_male = sbac(1415, 'ela', school, 5, 'Male')
ela_1415_gr5_female = sbac(1415, 'ela', school, 5, 'Female')
# #1516
ela_1516_gr5_total = sbac(1516, 'ela', school, 5, 'Total')
ela_1516_gr5_econdis = sbac(1516, 'ela', school, 5, 'Economically Disadvantaged')
ela_1516_gr5_ell = sbac(1516, 'ela', school, 5, 'Limited English Proficient')
ela_1516_gr5_ever_ell = sbac(1516, 'ela', school, 5, 'Ever Limited English Proficient')
ela_1516_gr5_SwD = sbac(1516, 'ela', school, 5, 'Students with Disabilities')
ela_1516_gr5_tag = sbac(1516, 'ela', school, 5, 'Talented and Gifted')
ela_1516_gr5_asian = sbac(1516, 'ela', school, 5, 'Asian')
ela_1516_gr5_hisp = sbac(1516, 'ela', school, 5, 'Hispanic/Latino')
ela_1516_gr5_white = sbac(1516, 'ela', school, 5, 'White')
ela_1516_gr5_multir = sbac(1516, 'ela', school, 5, 'Multi-Racial')
ela_1516_gr5_male = sbac(1516, 'ela', school, 5, 'Male')
ela_1516_gr5_female = sbac(1516, 'ela', school, 5, 'Female')
#1617
ela_1617_gr5_total = sbac(1617, 'ela', school, 5, 'Total')
ela_1617_gr5_econdis = sbac(1617, 'ela', school, 5, 'Economically Disadvantaged')
ela_1617_gr5_ell = sbac(1617, 'ela', school, 5, 'Limited English Proficient')
ela_1617_gr5_ever_ell = sbac(1617, 'ela', school, 5, 'Ever Limited English Proficient')
ela_1617_gr5_SwD = sbac(1617, 'ela', school, 5, 'Students with Disabilities')
ela_1617_gr5_tag = sbac(1617, 'ela', school, 5, 'Talented and Gifted')
ela_1617_gr5_asian = sbac(1617, 'ela', school, 5, 'Asian')
ela_1617_gr5_hisp = sbac(1617, 'ela', school, 5, 'Hispanic/Latino')
ela_1617_gr5_white = sbac(1617, 'ela', school, 5, 'White')
ela_1617_gr5_multir = sbac(1617, 'ela', school, 5, 'Multi-Racial')
ela_1617_gr5_male = sbac(1617, 'ela', school, 5, 'Male')
ela_1617_gr5_female = sbac(1617, 'ela', school, 5, 'Female')
#1718
ela_1718_gr5_total = sbac(1718, 'ela', school, 5, 'Total')
ela_1718_gr5_econdis = sbac(1718, 'ela', school, 5, 'Economically Disadvantaged')
ela_1718_gr5_ell = sbac(1718, 'ela', school, 5, 'Limited English Proficient')
ela_1718_gr5_ever_ell = sbac(1718, 'ela', school, 5, 'Ever Limited English Proficient')
ela_1718_gr5_SwD = sbac(1718, 'ela', school, 5, 'Students with Disabilities')
ela_1718_gr5_tag = sbac(1718, 'ela', school, 5, 'Talented and Gifted')
ela_1718_gr5_asian = sbac(1718, 'ela', school, 5, 'Asian')
ela_1718_gr5_hisp = sbac(1718, 'ela', school, 5, 'Hispanic/Latino')
ela_1718_gr5_white = sbac(1718, 'ela', school, 5, 'White')
ela_1718_gr5_multir = sbac(1718, 'ela', school, 5, 'Multi-Racial')
ela_1718_gr5_male = sbac(1718, 'ela', school, 5, 'Male')
ela_1718_gr5_female = sbac(1718, 'ela', school, 5, 'Female')

#SBAC: Math grade 3
#14-15
math_1415_gr3_total = sbac(1415, 'math', school, 3, 'Total')
math_1415_gr3_econdis = sbac(1415, 'math', school, 3, 'Economically Disadvantaged')
math_1415_gr3_ell = sbac(1415, 'math', school, 3, 'Limited English Proficient')
math_1415_gr3_ever_ell = sbac(1415, 'math', school, 3, 'Ever Limited English Proficient')
math_1415_gr3_SwD = sbac(1415, 'math', school, 3, 'Students with Disabilities')
math_1415_gr3_tag = sbac(1415, 'math', school, 3, 'Talented and Gifted')
math_1415_gr3_asian = sbac(1415, 'math', school, 3, 'Asian')
math_1415_gr3_hisp = sbac(1415, 'math', school, 3, 'Hispanic/Latino')
math_1415_gr3_white = sbac(1415, 'math', school, 3, 'White')
math_1415_gr3_multir = sbac(1415, 'math', school, 3, 'Multi-Racial')
math_1415_gr3_male = sbac(1415, 'math', school, 3, 'Male')
math_1415_gr3_female = sbac(1415, 'math', school, 3, 'Female')
#15-16
math_1516_gr3_total = sbac(1516, 'math', school, 3, 'Total')
math_1516_gr3_econdis = sbac(1516, 'math', school, 3, 'Economically Disadvantaged')
math_1516_gr3_ell = sbac(1516, 'math', school, 3, 'Limited English Proficient')
math_1516_gr3_ever_ell = sbac(1516, 'math', school, 3, 'Ever Limited English Proficient')
math_1516_gr3_SwD = sbac(1516, 'math', school, 3, 'Students with Disabilities')
math_1516_gr3_tag = sbac(1516, 'math', school, 3, 'Talented and Gifted')
math_1516_gr3_asian = sbac(1516, 'math', school, 3, 'Asian')
math_1516_gr3_hisp = sbac(1516, 'math', school, 3, 'Hispanic/Latino')
math_1516_gr3_white = sbac(1516, 'math', school, 3, 'White')
math_1516_gr3_multir = sbac(1516, 'math', school, 3, 'Multi-Racial')
math_1516_gr3_male = sbac(1516, 'math', school, 3, 'Male')
math_1516_gr3_female = sbac(1516, 'math', school, 3, 'Female')
#1617
math_1617_gr3_total = sbac(1617, 'math', school, 3, 'Total')
math_1617_gr3_econdis = sbac(1617, 'math', school, 3, 'Economically Disadvantaged')
math_1617_gr3_ell = sbac(1617, 'math', school, 3, 'Limited English Proficient')
math_1617_gr3_ever_ell = sbac(1617, 'math', school, 3, 'Ever Limited English Proficient')
math_1617_gr3_SwD = sbac(1617, 'math', school, 3, 'Students with Disabilities')
math_1617_gr3_tag = sbac(1617, 'math', school, 3, 'Talented and Gifted')
math_1617_gr3_asian = sbac(1617, 'math', school, 3, 'Asian')
math_1617_gr3_hisp = sbac(1617, 'math', school, 3, 'Hispanic/Latino')
math_1617_gr3_white = sbac(1617, 'math', school, 3, 'White')
math_1617_gr3_multir = sbac(1617, 'math', school, 3, 'Multi-Racial')
math_1617_gr3_male = sbac(1617, 'math', school, 3, 'Male')
math_1617_gr3_female = sbac(1617, 'math', school, 3, 'Female')
#1718
math_1718_gr3_total = sbac(1718, 'math', school, 3, 'Total')
math_1718_gr3_econdis = sbac(1718, 'math', school, 3, 'Economically Disadvantaged')
math_1718_gr3_ell = sbac(1718, 'math', school, 3, 'Limited English Proficient')
math_1718_gr3_ever_ell = sbac(1718, 'math', school, 3, 'Ever Limited English Proficient')
math_1718_gr3_SwD = sbac(1718, 'math', school, 3, 'Students with Disabilities')
math_1718_gr3_tag = sbac(1718, 'math', school, 3, 'Talented and Gifted')
math_1718_gr3_asian = sbac(1718, 'math', school, 3, 'Asian')
math_1718_gr3_hisp = sbac(1718, 'math', school, 3, 'Hispanic/Latino')
math_1718_gr3_white = sbac(1718, 'math', school, 3, 'White')
math_1718_gr3_multir = sbac(1718, 'math', school, 3, 'Multi-Racial')
math_1718_gr3_male = sbac(1718, 'math', school, 3, 'Male')
math_1718_gr3_female = sbac(1718, 'math', school, 3, 'Female')

#SBAC: math grade 5
#14-15
math_1415_gr5_total = sbac(1415, 'math', school, 5, 'Total')
math_1415_gr5_econdis = sbac(1415, 'math', school, 5, 'Economically Disadvantaged')
math_1415_gr5_ell = sbac(1415, 'math', school, 5, 'Limited English Proficient')
math_1415_gr5_ever_ell = sbac(1415, 'math', school, 5, 'Ever Limited English Proficient')
math_1415_gr5_SwD = sbac(1415, 'math', school, 5, 'Students with Disabilities')
math_1415_gr5_tag = sbac(1415, 'math', school, 5, 'Talented and Gifted')
math_1415_gr5_asian = sbac(1415, 'math', school, 5, 'Asian')
math_1415_gr5_hisp = sbac(1415, 'math', school, 5, 'Hispanic/Latino')
math_1415_gr5_white = sbac(1415, 'math', school, 5, 'White')
math_1415_gr5_multir = sbac(1415, 'math', school, 5, 'Multi-Racial')
math_1415_gr5_male = sbac(1415, 'math', school, 5, 'Male')
math_1415_gr5_female = sbac(1415, 'math', school, 5, 'Female')
#15-16
math_1516_gr5_total = sbac(1516, 'math', school, 5, 'Total')
math_1516_gr5_econdis = sbac(1516, 'math', school, 5, 'Economically Disadvantaged')
math_1516_gr5_ell = sbac(1516, 'math', school, 5, 'Limited English Proficient')
math_1516_gr5_ever_ell = sbac(1516, 'math', school, 5, 'Ever Limited English Proficient')
math_1516_gr5_SwD = sbac(1516, 'math', school, 5, 'Students with Disabilities')
math_1516_gr5_tag = sbac(1516, 'math', school, 5, 'Talented and Gifted')
math_1516_gr5_asian = sbac(1516, 'math', school, 5, 'Asian')
math_1516_gr5_hisp = sbac(1516, 'math', school, 5, 'Hispanic/Latino')
math_1516_gr5_white = sbac(1516, 'math', school, 5, 'White')
math_1516_gr5_multir = sbac(1516, 'math', school, 5, 'Multi-Racial')
math_1516_gr5_male = sbac(1516, 'math', school, 5, 'Male')
math_1516_gr5_female = sbac(1516, 'math', school, 5, 'Female')
#1617
math_1617_gr5_total = sbac(1617, 'math', school, 5, 'Total')
math_1617_gr5_econdis = sbac(1617, 'math', school, 5, 'Economically Disadvantaged')
math_1617_gr5_ell = sbac(1617, 'math', school, 5, 'Limited English Proficient')
math_1617_gr5_ever_ell = sbac(1617, 'math', school, 5, 'Ever Limited English Proficient')
math_1617_gr5_SwD = sbac(1617, 'math', school, 5, 'Students with Disabilities')
math_1617_gr5_tag = sbac(1617, 'math', school, 5, 'Talented and Gifted')
math_1617_gr5_asian = sbac(1617, 'math', school, 5, 'Asian')
math_1617_gr5_hisp = sbac(1617, 'math', school, 5, 'Hispanic/Latino')
math_1617_gr5_white = sbac(1617, 'math', school, 5, 'White')
math_1617_gr5_multir = sbac(1617, 'math', school, 5, 'Multi-Racial')
math_1617_gr5_male = sbac(1617, 'math', school, 5, 'Male')
math_1617_gr5_female = sbac(1617, 'math', school, 5, 'Female')
#1718
math_1718_gr5_total = sbac(1718, 'math', school, 5, 'Total')
math_1718_gr5_econdis = sbac(1718, 'math', school, 5, 'Economically Disadvantaged')
math_1718_gr5_ell = sbac(1718, 'math', school, 5, 'Limited English Proficient')
math_1718_gr5_ever_ell = sbac(1718, 'math', school, 5, 'Ever Limited English Proficient')
math_1718_gr5_SwD = sbac(1718, 'math', school, 5, 'Students with Disabilities')
math_1718_gr5_tag = sbac(1718, 'math', school, 5, 'Talented and Gifted')
math_1718_gr5_asian = sbac(1718, 'math', school, 5, 'Asian')
math_1718_gr5_hisp = sbac(1718, 'math', school, 5, 'Hispanic/Latino')
math_1718_gr5_white = sbac(1718, 'math', school, 5, 'White')
math_1718_gr5_multir = sbac(1718, 'math', school, 5, 'Multi-Racial')
math_1718_gr5_male = sbac(1718, 'math', school, 5, 'Male')
math_1718_gr5_female = sbac(1718, 'math', school, 5, 'Female')

In [51]:
growth_1718_math_none = growth_1718_math.fillna('None')
growth_1617_math_none = growth_1617_math.fillna('None')
growth_1516_math_none = growth_1516_math.fillna('None')
growth_1415_math_none = growth_1415_math.fillna('None')

growth_1718_ela_none = growth_1718_ela.fillna('None')
growth_1617_ela_none = growth_1617_ela.fillna('None')
growth_1516_ela_none = growth_1516_ela.fillna('None')
growth_1415_ela_none = growth_1415_ela.fillna('None')

In [52]:
#SBAC Growth
def math_growth(year, s_group):
    if year == 1617:
        val =  growth_1617_math_none[(growth_1617_math_none.school_id == school)][s_group].iloc[0]
    elif year == 1516:
        val = growth_1516_math_none[(growth_1516_math_none.school_id == school)][s_group].iloc[0]
    elif year == 1415:
        val = growth_1415_math_none[(growth_1415_math_none.school_id == school)][s_group].iloc[0]
    elif year == 1718:
        val = growth_1718_math_none[(growth_1718_math_none.school_id == school)][s_group].iloc[0]  
    else: 
        print("Year must be 1415, 1516, or 1617")
    if val == 'None':
        return ''
    else:
        return str( int( round(val*100, 0))) + '%'

#SBAC Growth
def ela_growth(year, s_group):
    if year == 1617:
        val =  growth_1617_ela_none[(growth_1617_ela_none.school_id == school)][s_group].iloc[0]
    elif year == 1516:
        val = growth_1516_ela_none[(growth_1516_ela_none.school_id == school)][s_group].iloc[0]
    elif year == 1415:
        val = growth_1415_ela_none[(growth_1415_ela_none.school_id == school)][s_group].iloc[0]
    elif year == 1718:
        val = growth_1718_ela_none[(growth_1718_ela_none.school_id == school)][s_group].iloc[0] 
    else: 
        print("Year must be 1415, 1516, 1617, or 1718")
    if val == 'None':
        return ''
    else:
        return str( int( round(val*100, 0))) + '%'

In [55]:
ela_growth(1718, 'All Students')

'57%'

In [56]:
#college readiness output
college_readiness_3 = []
college_readiness_3.append(['Grade 3 English Language Arts','1516','1617','1718', '', 'Grade 3 Math','1516','1617','1718'])
college_readiness_3.append(['Total',ela_1516_gr3_total,ela_1617_gr3_total,ela_1718_gr3_total, '', 'Total',math_1516_gr3_total,math_1617_gr3_total,math_1718_gr3_total])
college_readiness_3.append(['Economically disadvantaged',ela_1516_gr3_econdis,ela_1617_gr3_econdis,ela_1718_gr3_econdis, '', 'Economically disadvantaged',math_1516_gr3_econdis,math_1617_gr3_econdis,math_1718_gr3_econdis])
college_readiness_3.append(['English Language Learners',ela_1516_gr3_ell,ela_1617_gr3_ell,ela_1718_gr3_ell, '', 'English Language Learners',math_1516_gr3_ell,math_1617_gr3_ell,math_1718_gr3_ell])
college_readiness_3.append(['Ever English Language Learners',ela_1516_gr3_ever_ell,ela_1617_gr3_ever_ell,ela_1718_gr3_ever_ell, '', 'Ever English Language Learners',math_1516_gr3_ever_ell,math_1617_gr3_ever_ell,math_1718_gr3_ever_ell])
college_readiness_3.append(['Students with Disabilities',ela_1516_gr3_SwD,ela_1617_gr3_SwD,ela_1718_gr3_SwD, '', 'Students with Disabilities',math_1516_gr3_SwD,math_1617_gr3_SwD,math_1718_gr3_SwD])
college_readiness_3.append(['Talented and Gifted',ela_1516_gr3_tag,ela_1617_gr3_tag,ela_1718_gr3_tag, '', 'Talented and Gifted',math_1516_gr3_tag,math_1617_gr3_tag,math_1718_gr3_tag])
college_readiness_3.append(['Asian',ela_1516_gr3_asian,ela_1617_gr3_asian,ela_1718_gr3_asian, '', 'Asian',math_1516_gr3_asian,math_1617_gr3_asian,math_1718_gr3_asian])
college_readiness_3.append(['Hispanic',ela_1516_gr3_hisp,ela_1617_gr3_hisp,ela_1718_gr3_hisp, '', 'Hispanic',math_1516_gr3_hisp,math_1617_gr3_hisp,math_1718_gr3_hisp])
college_readiness_3.append(['White',ela_1516_gr3_white,ela_1617_gr3_white,ela_1718_gr3_white, '', 'White',math_1516_gr3_white,math_1617_gr3_white,math_1718_gr3_white])
college_readiness_3.append(['Multi-racial',ela_1516_gr3_multir,ela_1617_gr3_multir,ela_1718_gr3_multir, '', 'Multi-racial',math_1516_gr3_multir,math_1617_gr3_multir,math_1718_gr3_multir])
college_readiness_3.append(['Male',ela_1516_gr3_male,ela_1617_gr3_male,ela_1718_gr3_male, '', 'Male',math_1516_gr3_male,math_1617_gr3_male,math_1718_gr3_male])
college_readiness_3.append(['Female',ela_1516_gr3_female,ela_1617_gr3_female,ela_1718_gr3_female, '', 'Female',math_1516_gr3_female,math_1617_gr3_female,math_1718_gr3_female])

college_readiness_5 = []
college_readiness_5.append(['Grade 5 English Language Arts','1516','1617','1718', '', 'Grade 5 Math','1516','1617','1718'])
college_readiness_5.append(['Total',ela_1516_gr5_total,ela_1617_gr5_total,ela_1718_gr5_total, '', 'Total',math_1516_gr5_total,math_1617_gr5_total,math_1718_gr5_total])
college_readiness_5.append(['Economically disadvantaged',ela_1516_gr5_econdis,ela_1617_gr5_econdis,ela_1718_gr5_econdis, '', 'Economically disadvantaged',math_1516_gr5_econdis,math_1617_gr5_econdis,math_1718_gr5_econdis])
college_readiness_5.append(['English Language Learners',ela_1516_gr5_ell,ela_1617_gr5_ell,ela_1718_gr5_ell, '', 'English Language Learners',math_1516_gr5_ell,math_1617_gr5_ell,math_1718_gr5_ell])
college_readiness_5.append(['Ever English Language Learners',ela_1516_gr5_ever_ell,ela_1617_gr5_ever_ell,ela_1718_gr5_ever_ell, '', 'Ever English Language Learners',math_1516_gr5_ever_ell,math_1617_gr5_ever_ell,math_1718_gr5_ever_ell])
college_readiness_5.append(['Students with Disabilities',ela_1516_gr5_SwD,ela_1617_gr5_SwD,ela_1718_gr5_SwD, '', 'Students with Disabilities',math_1516_gr5_SwD,math_1617_gr5_SwD,math_1718_gr5_SwD])
college_readiness_5.append(['Talented and Gifted',ela_1516_gr5_tag,ela_1617_gr5_tag,ela_1718_gr5_tag, '', 'Talented and Gifted',math_1516_gr5_tag,math_1617_gr5_tag,math_1718_gr5_tag])
college_readiness_5.append(['Asian',ela_1516_gr5_asian,ela_1617_gr5_asian,ela_1718_gr5_asian, '', 'Asian',math_1516_gr5_asian,math_1617_gr5_asian,math_1718_gr5_asian])
college_readiness_5.append(['Hispanic',ela_1516_gr5_hisp,ela_1617_gr5_hisp,ela_1718_gr5_hisp, '', 'Hispanic',math_1516_gr5_hisp,math_1617_gr5_hisp,math_1718_gr5_hisp])
college_readiness_5.append(['White',ela_1516_gr5_white,ela_1617_gr5_white,ela_1718_gr5_white, '', 'White',math_1516_gr5_white,math_1617_gr5_white,math_1718_gr5_white])
college_readiness_5.append(['Multi-racial',ela_1516_gr5_multir,ela_1617_gr5_multir,ela_1718_gr5_multir, '', 'Multi-racial',math_1516_gr5_multir,math_1617_gr5_multir,math_1718_gr5_multir])
college_readiness_5.append(['Male',ela_1516_gr5_male,ela_1617_gr5_male,ela_1718_gr5_male, '', 'Male',math_1516_gr5_male,math_1617_gr5_male,math_1718_gr5_male])
college_readiness_5.append(['Female',ela_1516_gr5_female,ela_1617_gr5_female,ela_1718_gr5_female, '', 'Female',math_1516_gr5_female,math_1617_gr5_female,math_1718_gr5_female])

college_readiness_growth = []
college_readiness_growth.append(['Growth ELA', '1516', '1617', '1718', '', 'Growth Mathematics', '1516', '1617', '1718'])
college_readiness_growth.append(['All Students', ela_growth(1516, 'All Students'), ela_growth(1617, 'All Students'), ela_growth(1718, 'All Students'), '', 'All Students', math_growth(1516, 'All Students'), math_growth(1617, 'All Students'), math_growth(1718, 'All Students')])
college_readiness_growth.append(['Economically Disadvantaged', ela_growth(1516, 'Economically Disadvantaged'), ela_growth(1617, 'Economically Disadvantaged'), ela_growth(1718, 'Economically Disadvantaged'), '', 'Economically Disadvantaged', math_growth(1516, 'Economically Disadvantaged'), math_growth(1617, 'Economically Disadvantaged'), math_growth(1718, 'Economically Disadvantaged')])
college_readiness_growth.append(['English Language Learners', ela_growth(1516, 'English Language Learner'), ela_growth(1617, 'English Language Learner'), ela_growth(1718, 'English Language Learner'), '', 'English Language Learners', math_growth(1516, 'English Language Learner'), math_growth(1617, 'English Language Learner'), math_growth(1718, 'English Language Learner')])
college_readiness_growth.append(['Ever English Language Learners', '', '', '', '', 'Ever English Language Learners', '', '', ''])
college_readiness_growth.append(['Students with Disabilities', ela_growth(1516, 'Special Education'), ela_growth(1617, 'Special Education'), ela_growth(1718, 'Special Education'), '', 'Students with Disabilities', math_growth(1516, 'Special Education'), math_growth(1617, 'Special Education'), math_growth(1718, 'Special Education')])
college_readiness_growth.append(['Talented and Gifted', ela_growth(1516, 'Talented and Gifted'), ela_growth(1617, 'Talented and Gifted'), ela_growth(1718, 'Talented and Gifted'), '', 'Talented and Gifted', math_growth(1516, 'Talented and Gifted'), math_growth(1617, 'Talented and Gifted'), math_growth(1718, 'Talented and Gifted')])
college_readiness_growth.append(['Asian', ela_growth(1516, 'Asian'), ela_growth(1617, 'Asian'), ela_growth(1718, 'Asian'), '', 'Asian', math_growth(1516, 'Asian'), math_growth(1617, 'Asian'), math_growth(1718, 'Asian')])
college_readiness_growth.append(['Hispanic/Latino', ela_growth(1516, 'Hispanic/Latino'), ela_growth(1617, 'Hispanic/Latino'), ela_growth(1718, 'Hispanic/Latino'), '', 'Hispanic/Latino', math_growth(1516, 'Hispanic/Latino'), math_growth(1617, 'Hispanic/Latino'), math_growth(1718, 'Hispanic/Latino')])
college_readiness_growth.append(['White', ela_growth(1516, 'White'), ela_growth(1617, 'White'), ela_growth(1718, 'White'), '', 'White', math_growth(1516, 'White'), math_growth(1617, 'White'), math_growth(1718, 'White')])
college_readiness_growth.append(['Multi-racial', ela_growth(1516, 'Multiracial'), ela_growth(1617, 'Multiracial'), ela_growth(1718, 'Multiracial'), '', 'Multi-racial', math_growth(1516, 'Multiracial'), math_growth(1617, 'Multiracial'), math_growth(1718, 'Multiracial')])
college_readiness_growth.append(['Male', ela_growth(1516, 'Male'), ela_growth(1617, 'Male'), ela_growth(1718, 'Male'), '', 'Male', math_growth(1516, 'Male'), math_growth(1617, 'Male'), math_growth(1718, 'Male')])
college_readiness_growth.append(['Female', ela_growth(1516, 'Female'), ela_growth(1617, 'Female'), ela_growth(1718, 'Female'), '', 'Female', math_growth(1516, 'Female'), math_growth(1617, 'Female'), math_growth(1718, 'Female')])

In [130]:
# #temp no 1718
# #college readiness output
# college_readiness_3 = []
# college_readiness_3.append(['Grade 3 English Language Arts','1516','1617','1718', '', 'Grade 3 Math','1516','1617','1718'])
# college_readiness_3.append(['Total',ela_1516_gr3_total,ela_1617_gr3_total,'N/A', '', 'Total',math_1516_gr3_total,math_1617_gr3_total,'N/A'])
# college_readiness_3.append(['Economically disadvantaged',ela_1516_gr3_econdis,ela_1617_gr3_econdis,'N/A', '', 'Economically disadvantaged',math_1516_gr3_econdis,math_1617_gr3_econdis,'N/A'])
# college_readiness_3.append(['English Language Learners',ela_1516_gr3_ell,ela_1617_gr3_ell,'N/A', '', 'English Language Learners',math_1516_gr3_ell,math_1617_gr3_ell,'N/A'])
# college_readiness_3.append(['Ever English Language Learners',ela_1516_gr3_ever_ell,ela_1617_gr3_ever_ell,'N/A', '', 'Ever English Language Learners',math_1516_gr3_ever_ell,math_1617_gr3_ever_ell,'N/A'])
# college_readiness_3.append(['Students with Disabilities',ela_1516_gr3_SwD,ela_1617_gr3_SwD,'N/A', '', 'Students with Disabilities',math_1516_gr3_SwD,math_1617_gr3_SwD,'N/A'])
# college_readiness_3.append(['Talented and Gifted',ela_1516_gr3_tag,ela_1617_gr3_tag,'N/A', '', 'Talented and Gifted',math_1516_gr3_tag,math_1617_gr3_tag,'N/A'])
# college_readiness_3.append(['Asian',ela_1516_gr3_asian,ela_1617_gr3_asian,'N/A', '', 'Asian',math_1516_gr3_asian,math_1617_gr3_asian,'N/A'])
# college_readiness_3.append(['Hispanic',ela_1516_gr3_hisp,ela_1617_gr3_hisp,'N/A', '', 'Hispanic',math_1516_gr3_hisp,math_1617_gr3_hisp,'N/A'])
# college_readiness_3.append(['White',ela_1516_gr3_white,ela_1617_gr3_white,'N/A', '', 'White',math_1516_gr3_white,math_1617_gr3_white,'N/A'])
# college_readiness_3.append(['Multi-racial',ela_1516_gr3_multir,ela_1617_gr3_multir,'N/A', '', 'Multi-racial',math_1516_gr3_multir,math_1617_gr3_multir,'N/A'])
# college_readiness_3.append(['Male',ela_1516_gr3_male,ela_1617_gr3_male,'N/A', '', 'Male',math_1516_gr3_male,math_1617_gr3_male,'N/A'])
# college_readiness_3.append(['Female',ela_1516_gr3_female,ela_1617_gr3_female,'N/A', '', 'Female',math_1516_gr3_female,math_1617_gr3_female,'N/A'])

# college_readiness_5 = []
# college_readiness_5.append(['Grade 5 English Language Arts','1516','1617','1718', '', 'Grade 5 Math','1516','1617','1718'])
# college_readiness_5.append(['Total',ela_1516_gr5_total,ela_1617_gr5_total,'N/A', '', 'Total',math_1516_gr5_total,math_1617_gr5_total,'N/A'])
# college_readiness_5.append(['Economically disadvantaged',ela_1516_gr5_econdis,ela_1617_gr5_econdis,'N/A', '', 'Economically disadvantaged',math_1516_gr5_econdis,math_1617_gr5_econdis,'N/A'])
# college_readiness_5.append(['English Language Learners',ela_1516_gr5_ell,ela_1617_gr5_ell,'N/A', '', 'English Language Learners',math_1516_gr5_ell,math_1617_gr5_ell,'N/A'])
# college_readiness_5.append(['Ever English Language Learners',ela_1516_gr5_ever_ell,ela_1617_gr5_ever_ell,'N/A', '', 'Ever English Language Learners',math_1516_gr5_ever_ell,math_1617_gr5_ever_ell,'N/A'])
# college_readiness_5.append(['Students with Disabilities',ela_1516_gr5_SwD,ela_1617_gr5_SwD,'N/A', '', 'Students with Disabilities',math_1516_gr5_SwD,math_1617_gr5_SwD,'N/A'])
# college_readiness_5.append(['Talented and Gifted',ela_1516_gr5_tag,ela_1617_gr5_tag,'N/A', '', 'Talented and Gifted',math_1516_gr5_tag,math_1617_gr5_tag,'N/A'])
# college_readiness_5.append(['Asian',ela_1516_gr5_asian,ela_1617_gr5_asian,'N/A', '', 'Asian',math_1516_gr5_asian,math_1617_gr5_asian,'N/A'])
# college_readiness_5.append(['Hispanic',ela_1516_gr5_hisp,ela_1617_gr5_hisp,'N/A', '', 'Hispanic',math_1516_gr5_hisp,math_1617_gr5_hisp,'N/A'])
# college_readiness_5.append(['White',ela_1516_gr5_white,ela_1617_gr5_white,'N/A', '', 'White',math_1516_gr5_white,math_1617_gr5_white,'N/A'])
# college_readiness_5.append(['Multi-racial',ela_1516_gr5_multir,ela_1617_gr5_multir,'N/A', '', 'Multi-racial',math_1516_gr5_multir,math_1617_gr5_multir,'N/A'])
# college_readiness_5.append(['Male',ela_1516_gr5_male,ela_1617_gr5_male,'N/A', '', 'Male',math_1516_gr5_male,math_1617_gr5_male,'N/A'])
# college_readiness_5.append(['Female',ela_1516_gr5_female,ela_1617_gr5_female,'N/A', '', 'Female',math_1516_gr5_female,math_1617_gr5_female,'N/A'])

# college_readiness_growth = []
# college_readiness_growth.append(['Growth ELA', '1516', '1617', '1718', '', 'Growth Mathematics', '1516', '1617', '1718'])
# college_readiness_growth.append(['All Students', ela_growth(1516, 'All Students'), ela_growth(1617, 'All Students'), 'N/A', '', 'All Students', math_growth(1516, 'All Students'), math_growth(1617, 'All Students'), 'N/A'])
# college_readiness_growth.append(['Economically Disadvantaged', ela_growth(1516, 'Economically Disadvantaged'), ela_growth(1617, 'Economically Disadvantaged'), 'N/A', '', 'Economically Disadvantaged', math_growth(1516, 'Economically Disadvantaged'), math_growth(1617, 'Economically Disadvantaged'), 'N/A'])
# college_readiness_growth.append(['English Language Learners', ela_growth(1516, 'English Language Learner'), ela_growth(1617, 'English Language Learner'), 'N/A', '', 'English Language Learners', math_growth(1516, 'English Language Learner'), math_growth(1617, 'English Language Learner'), 'N/A'])
# college_readiness_growth.append(['Ever English Language Learners', '', '', '', '', 'Ever English Language Learners', '', '', ''])
# college_readiness_growth.append(['Students with Disabilities', ela_growth(1516, 'Special Education'), ela_growth(1617, 'Special Education'), 'N/A', '', 'Students with Disabilities', math_growth(1516, 'Special Education'), math_growth(1617, 'Special Education'), 'N/A'])
# college_readiness_growth.append(['Talented and Gifted', ela_growth(1516, 'Talented and Gifted'), ela_growth(1617, 'Talented and Gifted'), 'N/A', '', 'Talented and Gifted', math_growth(1516, 'Talented and Gifted'), math_growth(1617, 'Talented and Gifted'), 'N/A'])
# college_readiness_growth.append(['Asian', ela_growth(1516, 'Asian'), ela_growth(1617, 'Asian'), 'N/A', '', 'Asian', math_growth(1516, 'Asian'), math_growth(1617, 'Asian'), 'N/A'])
# college_readiness_growth.append(['Hispanic/Latino', ela_growth(1516, 'Hispanic/Latino'), ela_growth(1617, 'Hispanic/Latino'), 'N/A', '', 'Hispanic/Latino', math_growth(1516, 'Hispanic/Latino'), math_growth(1617, 'Hispanic/Latino'), 'N/A'])
# college_readiness_growth.append(['White', ela_growth(1516, 'White'), ela_growth(1617, 'White'), 'N/A', '', 'White', math_growth(1516, 'White'), math_growth(1617, 'White'), 'N/A'])
# college_readiness_growth.append(['Multi-racial', ela_growth(1516, 'Multiracial'), ela_growth(1617, 'Multiracial'), 'N/A', '', 'Multi-racial', math_growth(1516, 'Multiracial'), math_growth(1617, 'Multiracial'), 'N/A'])
# college_readiness_growth.append(['Male', ela_growth(1516, 'Male'), ela_growth(1617, 'Male'), 'N/A', '', 'Male', math_growth(1516, 'Male'), math_growth(1617, 'Male'), 'N/A'])
# college_readiness_growth.append(['Female', ela_growth(1516, 'Female'), ela_growth(1617, 'Female'), 'N/A', '', 'Female', math_growth(1516, 'Female'), math_growth(1617, 'Female'), 'N/A'])

In [57]:
part_rates = part_rates.sort_values(by=['part_rate'])
part_rates = part_rates.drop_duplicates(subset='school_id')

In [58]:
#round participation rates
def part_rate_adj( rate ):
    if rate > .99:
        return '>99%'
    else:
        return str( round(rate*100, 0)) + '%'
    
part_rates['rounded_part_rate'] = part_rates.part_rate.apply(part_rate_adj)

In [59]:
part_rates.head()

,school_id,school_name,grade,part_rate,rounded_part_rate
61,1179,William Walker Elementary School,4-5,0.006,1.0%
11,4671,Bonny Slope Elementary School,4-5,0.020,2.0%
39,5381,Mountainside High School,9-12,0.190,19.0%
25,4638,Health & Science School,9-12,0.260,26.0%
55,1188,Sunset High School,9-12,0.320,32.0%

In [60]:
std_survey_rate = part_rates[(part_rates['school_id'] == school)]['rounded_part_rate'].iloc[0]

In [61]:
print( std_survey_rate)

87.0%

In [62]:
#Students missing class
def missing(year):
    if year == 1415:
        val = missing_fewer[(missing_fewer['school_id'] == school)]['14-15']
    elif year == 1516:
        val = missing_fewer[(missing_fewer['school_id'] == school)]['15-16']
    elif year == 1617:
        val = missing_fewer[(missing_fewer['school_id'] == school)]['16-17']
    elif year == 1718:
        val = missing_fewer[(missing_fewer['school_id'] == school)]['17-18']
    else:
        print('incorrect year specified')
    if len(val) > 0:
        return str( int( round( (1 - val.iloc[0]) *100, 0))) + '%'
    else:
        return ''

In [63]:
#Students missing class
def disc_count(year):
    if year == 1415:
        val = disc_std_count[(disc_std_count['school_id'] == school)]['14-15']
    elif year == 1516:
        val = disc_std_count[(disc_std_count['school_id'] == school)]['15-16']
    elif year == 1617:
        val = disc_std_count[(disc_std_count['school_id'] == school)]['16-17']
    elif year == 1718:
        val = disc_std_count[(disc_std_count['school_id'] == school)]['17-18']
    else:
        print('incorrect year specified')
    if len(val) > 0:
        return val.iloc[0]
    else:
        return ''

def disc_days(year):
    if year == 1415:
        val = disc_class_days[(disc_class_days['school_id'] == school)]['14-15']
    elif year == 1516:
        val = disc_class_days[(disc_class_days['school_id'] == school)]['15-16']
    elif year == 1617:
        val = disc_class_days[(disc_class_days['school_id'] == school)]['16-17']
    elif year == 1718:
        val = disc_class_days[(disc_class_days['school_id'] == school)]['17-18']
    else:
        print('incorrect year specified')
    if len(val) > 0:
        return val.iloc[0]
    else:
        return ''

def se_adult_percent(year):
    if year == 1213:
        val = std_adult_cares[(std_adult_cares['school_id'] == school)]['12-13']
    elif year == 1314:
        val = std_adult_cares[(std_adult_cares['school_id'] == school)]['13-14']
    elif year == 1415:
        val = std_adult_cares[(std_adult_cares['school_id'] == school)]['14-15']
    elif year == 1516:
        val = std_adult_cares[(std_adult_cares['school_id'] == school)]['15-16']
    elif year == 1617:
        val = std_adult_cares[(std_adult_cares['school_id'] == school)]['16-17']
    elif year == 1718:
        val = std_adult_cares[(std_adult_cares['school_id'] == school)]['17-18']
    else:
        print('incorrect year specified')
    if val.iloc[0] == '':
        return ''
    else:
        return str( int( round(val.iloc[0]*100, 0))) + '%'

In [64]:
se_adult_percent(1718)

'89%'

In [65]:
def parent_inf_value(year):
    if year == 1213:
        val = parents_six_measures[(parents_six_measures['school_id'] == school)]['12-13']
    elif year == 1314:
        val = parents_six_measures[(parents_six_measures['school_id'] == school)]['13-14']
    elif year == 1415:
        val = parents_six_measures[(parents_six_measures['school_id'] == school)]['14-15']
    elif year == 1516:
        val = parents_six_measures[(parents_six_measures['school_id'] == school)]['15-16']
    elif year == 1617:
        val = parents_six_measures[(parents_six_measures['school_id'] == school)]['16-17']
    elif year == 1718:
        val = parents_six_measures[(parents_six_measures['school_id'] == school)]['17-18']
    else:
        print('incorrect year specified')
    if len(val) > 0:
        return str( int( round(val.iloc[0]*100, 0))) + '%'
    else:
        return ''

In [66]:
def staff_voice_heard(year):
    if year == 1415:
        val = staff_voice[(staff_voice['school_id'] == school)]['14-15']
    elif year == 1516:
        val = staff_voice[(staff_voice['school_id'] == school)]['15-16']
    elif year == 1617:
        val = staff_voice[(staff_voice['school_id'] == school)]['16-17']
    elif year == 1718:
        val = staff_voice[(staff_voice['school_id'] == school)]['17-18']
    else:
        print('incorrect year specified')
    if len(val) > 0:
        return str( int( round(val.iloc[0], 0))) + '%'
    else:
        return ''

In [67]:
survey_part_output = []
survey_part_output.append(['/n'])
survey_part_output.append(['Student Survey participation rate:', std_survey_rate])

In [68]:
#last section
measures_section = []
measures_section.append(['','15-16','16-17','17-18', '', '', '15-16', '16-17', '17-18'])
measures_section.append(['Students missing fewer than 10 days of school', missing(1516), missing(1617), missing(1718), '', 'Students reporting that at least one adult cares about them', se_adult_percent(1516), se_adult_percent(1617), se_adult_percent(1718)])
measures_section.append(['Students missing class due to suspensions or expulsion', disc_count(1516), disc_count(1617), disc_count(1718), '', 'Parents reporting they feel informed and valued as active partners in their child\'s education', parent_inf_value(1516), parent_inf_value(1617), parent_inf_value(1718)])
measures_section.append(['Number of class days missed due to suspension or expulsion', disc_days(1516), disc_days(1617), disc_days(1718), '', 'Teachers and staff reporting they contribute to school decision making', staff_voice_heard(1516), staff_voice_heard(1617), staff_voice_heard(1718)])

In [69]:
import csv

In [70]:
#change file name and location!
#to work for jon - replace with open('C:/Users/bakerjul/Desktop/sip_output.csv', 'wb') as csvfile:
with open('C:/Users/bakerjul/Desktop/sip_output.csv', 'w', newline='') as csvfile:
    output = csv.writer(csvfile)
    output.writerows(principal_output)
    output.writerows(ode_output)
    output.writerows(oka_output)
    output.writerows(college_readiness_3)
    output.writerows(college_readiness_5)
    output.writerows(college_readiness_growth)
    output.writerows(survey_part_output)
    output.writerows(measures_section)